export type NpcRegister = 'cozy' | 'medieval' | 'cyber' | 'fantasy';

export interface NpcPersonalityData {
  warmth: number;
  bluntness: number;
  humor: number;
  greed: number;
  superstition: number;
  talkative: number;
}

export type NpcMemoryKind =
  | 'meet' | 'record' | 'rare' | 'promise' | 'gift' | 'absence'
  | 'activity' | 'gossip';

export interface NpcMemoryData {
  kind: NpcMemoryKind;
  day: number;
  weight: number;
  subject?: string;
  value?: number;
}

/** The persistent part of one villager's relationship with one player. */
export interface NpcMindState {
  memories: NpcMemoryData[];
  met: number;
  lastDay: number;
}

export interface NpcTalkWorld {
  day: number;
  phase: 'pagi' | 'siang' | 'senja' | 'malam';
  rain: number;
  place: string;
  playerName: string;
  lastCatch: { label: string; cm: number } | null;
  recordCm: number;
  recordLabel: string;
  species: number;
  coins: number;
  others: number;
}

export interface NpcTalkTurn {
  npc: string;
  player: string;
}

export interface NpcTalkRequest {
  npc: {
    id: string;
    name: string;
    register: NpcRegister;
    personality: NpcPersonalityData;
    mood: number;
    mind: NpcMindState;
  };
  world: NpcTalkWorld;
  history: NpcTalkTurn[];
}

/** A turn generated by the model. `memory` is intentionally narrow: the
 * deterministic game systems still own witnessed catches/absence/etc.; AI is
 * only allowed to create memories that arise from the conversation itself. */
export interface NpcTalkResponse {
  line: string;
  choices: string[];
  end: boolean;
  memory?: {
    kind: 'promise' | 'gift';
    subject: string;
    weight: number;
  };
}
